export interface CatalogItem {
  id: string;
  slug: string;
  title: string;
  type: "series" | "movie";
  genres: string[];
  rating: number;
  year: number;
  episodes?: number;
  badge?: string;
  imageSrc: string;
  description: string;
}

export const catalogItems: ReadonlyArray<CatalogItem> = [
  {
    id: "demon-slayer",
    slug: "demon-slayer",
    title: "Demon Slayer",
    type: "series",
    genres: ["action", "fantasy"],
    rating: 8.7,
    year: 2019,
    episodes: 44,
    badge: "Top 10",
    imageSrc: "/images/promo.png",
    description: "A young swordsman fights demons to save his sister after their family is slaughtered.",
  },
  {
    id: "jujutsu-kaisen",
    slug: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    type: "series",
    genres: ["action", "psychological"],
    rating: 8.6,
    year: 2020,
    episodes: 47,
    badge: "Trending",
    imageSrc: "/images/placeholder.png",
    description: "A high schooler swallows a cursed finger to save his friends, gaining immense power.",
  },
  {
    id: "frieren",
    slug: "frieren-beyond-journeys-end",
    title: "Frieren: Beyond Journey's End",
    type: "series",
    genres: ["fantasy", "classic"],
    rating: 9.1,
    year: 2023,
    episodes: 28,
    badge: "Editor's Pick",
    imageSrc: "/images/card.png",
    description: "An elven mage reflects on a lifetime of adventure in a world after the demon king's defeat.",
  },
  {
    id: "spy-x-family",
    slug: "spy-x-family",
    title: "Spy x Family",
    type: "series",
    genres: ["comedy", "action"],
    rating: 8.2,
    year: 2022,
    episodes: 37,
    imageSrc: "/images/placeholder1.png",
    description: "A spy, an assassin, and a telepathic girl form a fake family — none knowing each other's secrets.",
  },
  {
    id: "solo-leveling",
    slug: "solo-leveling",
    title: "Solo Leveling",
    type: "series",
    genres: ["action", "isekai"],
    rating: 8.4,
    year: 2024,
    episodes: 24,
    badge: "New",
    imageSrc: "/images/promo.png",
    description: "The world's weakest hunter awakens a power that lets him level up alone.",
  },
  {
    id: "attack-on-titan",
    slug: "attack-on-titan",
    title: "Attack on Titan",
    type: "series",
    genres: ["action", "psychological", "thriller"],
    rating: 9.0,
    year: 2013,
    episodes: 87,
    badge: "Legendary",
    imageSrc: "/images/placeholder.png",
    description: "Humanity's last survivors fight giant humanoid creatures from behind massive walls.",
  },
  {
    id: "death-note",
    slug: "death-note",
    title: "Death Note",
    type: "series",
    genres: ["psychological", "thriller"],
    rating: 9.0,
    year: 2006,
    episodes: 37,
    badge: "Classic",
    imageSrc: "/images/card.png",
    description: "A genius student finds a supernatural notebook that kills anyone whose name is written in it.",
  },
  {
    id: "your-lie-in-april",
    slug: "your-lie-in-april",
    title: "Your Lie in April",
    type: "series",
    genres: ["romance", "school"],
    rating: 8.7,
    year: 2014,
    episodes: 22,
    imageSrc: "/images/placeholder1.png",
    description: "A piano prodigy rediscovers music through a free-spirited violinist.",
  },
  {
    id: "chainsaw-man",
    slug: "chainsaw-man",
    title: "Chainsaw Man",
    type: "series",
    genres: ["action", "psychological"],
    rating: 8.5,
    year: 2022,
    episodes: 12,
    badge: "Cult Hit",
    imageSrc: "/images/promo.png",
    description: "A debt-ridden teen merges with his chainsaw devil dog to become a devil hunter.",
  },
  {
    id: "vinland-saga",
    slug: "vinland-saga",
    title: "Vinland Saga",
    type: "series",
    genres: ["action", "classic"],
    rating: 8.8,
    year: 2019,
    episodes: 48,
    imageSrc: "/images/placeholder.png",
    description: "A Norse warrior pursues revenge across a war-torn medieval Europe.",
  },
  {
    id: "suzume",
    slug: "suzume",
    title: "Suzume",
    type: "movie",
    genres: ["fantasy", "romance"],
    rating: 8.1,
    year: 2022,
    badge: "Film",
    imageSrc: "/images/card.png",
    description: "A girl chases a mysterious young man through Japan, closing ancient doors that unleash disasters.",
  },
  {
    id: "your-name",
    slug: "your-name",
    title: "Your Name",
    type: "movie",
    genres: ["romance", "fantasy"],
    rating: 8.9,
    year: 2016,
    badge: "Masterpiece",
    imageSrc: "/images/placeholder1.png",
    description: "Two strangers find themselves mysteriously swapping bodies — until they discover the truth.",
  },
  {
    id: "spirited-away",
    slug: "spirited-away",
    title: "Spirited Away",
    type: "movie",
    genres: ["fantasy", "classic"],
    rating: 9.3,
    year: 2001,
    badge: "All-Time Best",
    imageSrc: "/images/promo.png",
    description: "A young girl becomes trapped in a mysterious spirit world and must work to free her parents.",
  },
  {
    id: "akira",
    slug: "akira",
    title: "Akira",
    type: "movie",
    genres: ["action", "thriller", "classic"],
    rating: 8.0,
    year: 1988,
    badge: "Legendary",
    imageSrc: "/images/placeholder.png",
    description: "In a dystopian Neo-Tokyo, a biker and his childhood friend get entangled in a government experiment.",
  },
  {
    id: "devil-may-cry",
    slug: "devil-may-cry",
    title: "Devil May Cry",
    type: "movie",
    genres: ["action", "fantasy"],
    rating: 7.8,
    year: 2024,
    badge: "New",
    imageSrc: "/images/card.png",
    description: "Half-demon mercenary Dante hunts supernatural threats in a stylish action epic.",
  },
  {
    id: "solo-leveling-reawakening",
    slug: "solo-leveling-reawakening",
    title: "Solo Leveling: ReAwakening",
    type: "movie",
    genres: ["action", "isekai"],
    rating: 8.0,
    year: 2024,
    badge: "Event Film",
    imageSrc: "/images/placeholder1.png",
    description: "The definitive recap film for Solo Leveling, followed by a new arc introduction.",
  },
];

export const genres: ReadonlyArray<{ id: string; label: string; emoji: string }> = [
  { id: "all", label: "All", emoji: "✦" },
  { id: "action", label: "Action", emoji: "⚔️" },
  { id: "fantasy", label: "Fantasy", emoji: "🌙" },
  { id: "romance", label: "Romance", emoji: "🌸" },
  { id: "psychological", label: "Mind Games", emoji: "🧠" },
  { id: "thriller", label: "Thriller", emoji: "🔪" },
  { id: "comedy", label: "Comedy", emoji: "😂" },
  { id: "isekai", label: "Isekai", emoji: "🌀" },
  { id: "school", label: "School Life", emoji: "🏫" },
  { id: "classic", label: "Classics", emoji: "🏆" },
];
